import React, { useState } from "react";
import {
  Box,
  Typography,
  Modal,
  Grid,
  Button,
  Checkbox,
  FormControlLabel,
} from "@mui/material";
import TableWithInputs from "./TableWithInputs";
import CustomerSelect from "./CustomerSelect";
import SpacingWrapper from "../util/SpacingWrapper";
import PaymentTerms from "./PaymentTerms";
import Plant from "./Plant";
import DateSelector from "./DateSelector";
import CheckBoxOutlineBlankIcon from "@mui/icons-material/CheckBoxOutlineBlank";
import CheckBoxIcon from "@mui/icons-material/CheckBox";
import RemarkBox from "./RemarkBox";

const modalStyle = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: "90vw",
  height: "80vh", // Adjusted for better layout
  bgcolor: "background.paper",
  border: "2px solid #000",
  boxShadow: 24,
  p: 4,
  overflowY: "auto", // In case of overflow
};

const CreateRequestModal = ({ open, handleClose }) => {
  // Simplified example, implement your form submission logic here
  const handleSubmit = (event) => {
    event.preventDefault();
    //console.log("Form data", { tableRows });
    console.log("Selected customers", selectedCustomers);
    console.log("Selected consignees", selectedConsignees);
    handleClose(); // Close modal after submission, you might want to do this after successful submission
    if (checkBoxEnabled && isChecked) {
      oneToManyMapping(selectedCustomers, selectedConsignees);
    } else {
      oneToManyMapping(selectedCustomers, selectedConsignees);
    }
  };

  const [selectedCustomers, setSelectedCustomers] = useState([]);
  const [selectedConsignees, setSelectedConsignees] = useState([]);

  const [checkBoxEnabled, setCheckBoxEnabled] = useState(false);
  const [isChecked, setIsChecked] = useState(false);

  const [tableRowsData, setTableRowsData] = useState([]);
  const CheckCheckBox = () => {
    if (
      selectedCustomers.length === selectedConsignees.length &&
      selectedCustomers.length == 0
    ) {
      setCheckBoxEnabled(false);
    }
    if (selectedConsignees.length === selectedCustomers.length) {
      setCheckBoxEnabled(true);
    } else {
      setCheckBoxEnabled(false);
    }
  };

  const handleCheckboxChange = (event) => {
    setIsChecked(event.target.checked);
  };

  const oneToManyMapping = (array1, array2) => {
    // Generating the mapped array using nested loops
    const mappedArray = array1
      .map((item1) => {
        return array2.map((item2) => {
          return [item1, item2];
        });
      })
      .flat(); // Use flat() to flatten the array of arrays generated by the double map

    console.log(mappedArray);
    console.log(tableRowsData);
  };

  const oneToOneMapping = (array1, array2) => {
    // Generating the mapped array using nested loops
    const maxLength = Math.min(array1.length, array2.length);
    const mappedArray = Array.from({ length: maxLength }, (_, i) => [
      array1[i],
      array2[i],
    ]);

    console.log(mappedArray);
    console.log(tableRowsData);
  };

  const setTableRowsDataFunction = (data) => {
    setTableRowsData(data);
  };

  return (
    <Modal
      open={open}
      onClose={handleClose}
      aria-labelledby="create-request-modal"
      aria-describedby="create-request-modal-description"
    >
      <Box sx={modalStyle} component="form" onSubmit={handleSubmit}>
        <Typography
          id="create-request-modal-title"
          variant="h6"
          component="h2"
          marginBottom={2}
        >
          Create New Request
        </Typography>
        <Grid container spacing={2}>
          <Grid item xs={6}>
            <SpacingWrapper space="12px" />
            <CustomerSelect
              id={1}
              name={"customer"}
              setSelection={setSelectedCustomers}
              checkCheckBox={CheckCheckBox}
            />
            <SpacingWrapper space="12px" />
            <FormControlLabel
              control={
                <Checkbox
                  disabled={selectedCustomers.length === 0 || checkBoxEnabled}
                  icon={<CheckBoxOutlineBlankIcon fontSize="medium" />}
                  checkedIcon={<CheckBoxIcon fontSize="medium" />}
                  checked={isChecked}
                  onChange={handleCheckboxChange}
                />
              }
              label="All customers for all consignees"
            />{" "}
            <SpacingWrapper space="12px" />
            <CustomerSelect id={3} name={"end use"} />
            <SpacingWrapper space="12px" />
            <Plant />
            <SpacingWrapper space="12px" />
            <PaymentTerms />
            <SpacingWrapper space="12px" />
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <DateSelector name={"valid from"} />
              </Grid>
              <Grid item xs={6}>
                <DateSelector name={"valid to"} />
              </Grid>
            </Grid>
            <SpacingWrapper space="12px" />
          </Grid>
          <Grid item xs={6}>
            <SpacingWrapper space="12px" />
            <CustomerSelect
              id={2}
              name={"consignee"}
              setSelection={setSelectedConsignees}
              checkCheckBox={CheckCheckBox}
            />

            <SpacingWrapper space="12px" />

            <SpacingWrapper space="61.5px" />

            {/* Additional inputs and layout for column 2 */}
          </Grid>
        </Grid>

        <SpacingWrapper space="24px" />
        <Typography>Select pricing conditions</Typography>
        <TableWithInputs setTableRowsDataFunction={setTableRowsDataFunction} />
        <SpacingWrapper space="24px" />
        <RemarkBox />
        <Box sx={{ display: "flex", justifyContent: "space-between", mt: 2 }}>
          <Button onClick={handleClose} color="primary">
            Close
          </Button>
        </Box>
        <Box textAlign="center" marginTop={2}>
          <Button type="submit" variant="contained">
            Submit
          </Button>
          {/* <IconButton onClick={handleAddRow}>
            <AddCircleIcon />
          </IconButton> */}
        </Box>
      </Box>
    </Modal>
  );
};

export default CreateRequestModal;
